const ADD = "ADD";
const SEARCH = "SEARCH";
const FILTER = "FILTER";
const DONE = "DONE";
const DELETE = "DELETE";
const IMPORTANT = "IMPORTANT";
const SET_LIST = "SET_LIST";

export { ADD, SEARCH, FILTER, DELETE, DONE, IMPORTANT, SET_LIST };
